#docker-compose up -d
#docker-compose down #mantem os dados
#docker-compose down --volumes #elimina os dados
version: "3.8"

services:
  # Database
  db:
    image: mysql:5.7
    container_name: MySQL-Wp-Devs
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql

  # SGBD
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpMyAdmin-Wp-Devs
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    restart: always
    ports:
      - "8081:80"

  # Aplicação
  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.2-php8.0-apache
    container_name: WordPress-Wp-Devs
    volumes:
      - ./:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # - ./wp-content:/var/www/html/wp-content
    ports:
      - 8181:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
